### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by NoModesty** [kaminaris/MaxDps-Rogue#1]
Please update for version 8.1.0.29297

**Comment by ar1a** [comment]
what's failing?

**Comment by NoModesty** [comment]
I'm not sure its just every once in a while it says that it is out of date
and needs to be disabled. It only does it every once and a while more
frequently when the new patch first dropped, which is when i first
requested the update. I don't know anything about how to make an add-on let
alone figure out what is failing. Sorry I couldn't be more specific.
